name: test_task_github
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  auto_route: ^3.1.3
  bloc: ^8.0.1
  dio: ^4.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.3.0
  logger: ^1.1.0
  retrofit: ^3.0.0
  share_plus: ^3.0.4
  webview_flutter: ^2.3.1

dev_dependencies:
  auto_route_generator: ^3.1.0
  build_runner: ^2.1.5
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.1
  retrofit_generator: ^3.0.0+2

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  main_locale: ru
  class_name: Strings
  arb_dir: l10n
